### ISSUE TITLE
aioredis.exceptions.ResponseError: syntax error

### ISSUE THREAD

**Issue by cheesycod** [aio-libs/aioredis-py#1032]
aioredis gives a syntax error when I set and use keepttl:

await redis_db.set(f"identity-{id}", orjson.dumps(rl), ex = 60*60*24, keepttl = True)

**Comment by abrookins** [comment]
The problem with your command is that you can't pass both `EX` (or `PX`) with the `KEEPTTL` option. This is because `KEEPTTL` keeps the existing TTL, while EX and PX change it, so the options conflict. You'll also get a syntax error in redis-cli:

```
127.0.0.1:6379> set a 2 ex 1 keepttl
(error) ERR syntax error
```

The exclusive nature of the commands is apparent in the autocomplete within redis-cli:

```
127.0.0.1:6379> set a value [EX seconds|PX milliseconds|KEEPTTL] [NX|XX]
```

However, the actual docs on the command don't seem to mention this! https://redis.io/commands/set
