### ISSUE TITLE
socket_connect_timeout is not set in UnixDomainSocketConnection, leads to an error

### ISSUE THREAD

**Issue by Yolley** [aio-libs/aioredis-py#1060]
On `2.0.0b1` version `UnixDomainSocketConnection` inherits from `Connection `, which has `disconnect` method https://github.com/aio-libs/aioredis-py/blob/master/aioredis/connection.py#L754, which relies on `socket_connect_timeout `, but this property is not set in `UnixDomainSocketConnection`, which leads to an error in my environment:
```
> File "/usr/local/lib/python3.8/site-packages/aioredis/connection.py", line 754, in disconnect
    async with async_timeout.timeout(self.socket_connect_timeout):
               │             │       │    └ <member 'socket_connect_timeout' of 'Connection' objects>
               │             │       └ UnixDomainSocketConnection<path=/tmp/tmpb312to6t/redis.socket,db=5>
               │             └ <class 'async_timeout.timeout'>
               └ <module 'async_timeout' from '/usr/local/lib/python3.8/site-packages/async_timeout/__init__.py'>

AttributeError: socket_connect_timeout
```
I am not sure how we should deal with it,  it seems that this method uses a different approach than the same method from `redis-py` (`socket_connect_timeout` is not used in `disconnect` in `redis-py` module).

**Comment by Andrew-Chen-Wang** [comment]
Good catch! The class you are using, UnixDomainSocketConnection, overrides the constructor where we don't set the attribute socket_connect_timeout. In redis-py, UnixDomainSocketConnection also does not have this attribute, but technically: `self.socket_connect_timeout = socket_connect_timeout or socket_timeout` so in the UnixDomainSocketConnection class, we can add in our constructor `self.socket_time = self.socket_connect_timeout = socket_timeout`.

We might just need new input parameters though, like `socket_disconnect_timeout` since the redis-py implementation doesn't include a "timeout". @seandstewart @abrookins thoughts?

**Comment by abrookins** [comment]
I'll check this out tomorrow!

**Comment by abrookins** [comment]
@Andrew-Chen-Wang I think we should add the parameter and set it. That's what I did in my PR.
