### ISSUE TITLE
Enable Mypy

### ISSUE THREAD

**Issue by Dreamsorcerer** [aio-libs/aioredis-py#1098]
It seems we are exposing types in the library, but many parts are still missing annotations. We should look at filling in the remaining annotations and enable mypy checking in the CI.

If any one wants to volunteer for this before I take a look, feel free to add me to any PRs.

**Comment by Andrew-Chen-Wang** [comment]
@Dreamsorcerer floor's yours: #1099 branch off there and should be good to go (since it's your first time contributing, I won't be able to run the CI for you every time you commit, so please run everything on your side beforehand; I will approve your pushes once in awhile and I think others would gladly help if you make small commits overtime rather than getting everything done in one sitting). Thanks a ton!

**Comment by Dreamsorcerer** [comment]
Actually thought I already had access, but it appears this is one of the few repos not granted to aiohttp-dev team. Anyway, I'm updating a couple of other repos at the moment (aiohttp-session right now), so I'll get round to it later if you've not already done so.

**Comment by Andrew-Chen-Wang** [comment]
@Dreamsorcerer gotcha thanks a ton! Note that we'll be changing `lock.py` completely since it doesn't really have the correct impl, so I wouldn't spend too much or any time on that.
