### ISSUE TITLE
aioredis pipeline implementation problem

### ISSUE THREAD

**Issue by Hesarn** [aio-libs/aioredis-py#650]
Hi
i was taking a  look at the way that the pipeline has implemented in aioredis, and it seems that the way it is implemented it's not actually a redis pipeline, and it just queues commands in a list in code and at the execution time, it executes **each one of commands separately** on a single connection to redis.

This funcition is my problem.

```py3
    def _send_pipeline(self, conn):
        with conn._buffered():
            for fut, cmd, args, kw in self._pipeline:
                try:
                    result_fut = conn.execute(cmd, *args, **kw)  # --- execute each command separately
                    result_fut.add_done_callback(
                        functools.partial(self._check_result, waiter=fut))
                except Exception as exc:
                    fut.set_exception(exc)
                else:
                    yield result_fut
```

please correct me if i'me wrong.

thanks

**Comment by popravich** [comment]
Hi,
You missed `with conn._buffered()` line.
In earlier version of aioredis `_send_pipeline` indeed was sending commands one by one.

**Comment by nrccua-timr** [comment]
@popravich I'm also seeing this performance benchmark, where aioredis is 75% slower than redis.  Been using aioredis for the last six months but reconsidering now since this is such a performance hit.  We need to add hset | expire in transactions in the order of thousands per second.  Also we need to use the hget_all with pipeline(False) which doesn't even seem to be an option.

**Comment by Andrew-Chen-Wang** [comment]
@nrccua-timr Do you mind taking a look at #891 I'm busy with school, but I've been meaning to get a performance benchmark. If you don't mind trying out the above code and benchmark again but using that PR for aioredis. Thanks!

**Comment by seandstewart** [comment]
> @nrccua-timr Do you mind taking a look at #891 I'm busy with school, but I've been meaning to get a performance benchmark. If you don't mind trying out the above code and benchmark again but using that PR for aioredis. Thanks!

I'm guessing it will be about the same, given the impl in #891 is nearly identical to redis-py's and actually reduces network bandwidth quite a bit. In the current impl we just spawn a bunch of individual tasks, it's essentially a fancy `asyncio.gather`. But that will cause a lot of latency if we 1) overload the server with requests or 2) schedule more tasks than available connections in the pool or 3) a mix of both (1) & (2).

**Comment by Andrew-Chen-Wang** [comment]
@seandstewart Perhaps. Really the only benchmark that I think a lot of people are looking at when choosing a redis client is the one created by this repository's author: https://github.com/popravich/python-redis-benchmark

Besides the blatant bias, I'd like to see if this new implementation's benchmark live up to its name. People expect the latency between cache and server and server processing to be as minimal as possible, so having results in my opinion would be helpful.

> But that will cause a lot of latency if we 1) overload the server with requests or 2) schedule more tasks than available connections in the pool or 3) a mix of both (1) & (2).

As in the requests to the Redis server or like a web server? If it's the latter, then I can't imagine overloading the server being too big of an issue since production environments are on workers spawning independent threads. Same with point 2.

**Comment by seandstewart** [comment]
> @seandstewart Perhaps. Really the only benchmark that I think a lot of people are looking at when choosing a redis client is the one created by this repository's author: https://github.com/popravich/python-redis-benchmark
> 
> Besides the blatant bias, I'd like to see if this new implementation's benchmark live up to its name. People expect the latency between cache and server and server processing to be as minimal as possible, so having results in my opinion would be helpful.
> 
> > But that will cause a lot of latency if we 1) overload the server with requests or 2) schedule more tasks than available connections in the pool or 3) a mix of both (1) & (2).
> 
> As in the requests to the Redis server or like a web server? If it's the latter, then I can't imagine overloading the server being too big of an issue since production environments are on workers spawning independent threads. Same with point 2.

I should clarify (1). By *overloading* I simply mean that Redis processes all incoming queries sequentially (barring a small number of very explicit exceptions). If you send in 5000 queries at once, Redis will respond to each query in-turn. Using a pipeline allows Redis to respond in bulk, using the multi-bulk response protocol, which is more efficient in terms of CPU and IO, since Redis can optimize and pack the result into a single response.

**Comment by nrccua-timr** [comment]
@Andrew-Chen-Wang so I tested the PR branch sean/aioredis-redis-py-compliance and the time was approx the same as using redis-py, so much better than aioredis version 1.3.1. 

sync time = 0.14842700958251953
async time = 0.14449310302734375
-3.9339065551757812

However, it seems like the aioredis commands no longer need the await clause?

**Comment by Andrew-Chen-Wang** [comment]
@seandstewart Ah yes then that makes sense. Thanks for clarifying!

@nrccua-timr Not... sure? I thought they still do since you need to await for any kind of latency bit... Unless we missed some function during the port from redis-py to aioredis. Ik the docs haven't exactly been merged yet, but take a look here: https://github.com/aio-libs/aioredis/pull/891/files#diff-9369a12eda54eb33dac17bd4686d9a0ece704711b82671e0e77a9230d02db3d3R8-R10

I'm not exactly an expert on this PR since I've never found the time to properly take a gander, but hopefully that's how it works?

**Comment by seandstewart** [comment]
The pipelined commands no longer return tasks, instead they return the pipeline instance, just like in redis-py. The final execute requires an `await` however, since it's IO.

**Comment by nrccua-timr** [comment]
@Andrew-Chen-Wang I tested pipeline.execute() and redis_instance.set('python', 'go') and both no longer want the await. Maybe I'm doing something wrong when installing:

pip install git+https://github.com/aio-libs/aioredis.git@sean/aioredis-redis-py-compliance

By the way, this PR https://github.com/aio-libs/aioredis/pull/891 looks awesome and will be great for the longevity of the project and staying up to date.  I've created this project that leverages aioredis among other things:  https://pypi.org/project/aioradio/

**Comment by nrccua-timr** [comment]
@seandstewart so the following code is the benchmark I had to use (using fakeredis) with the PR:

`import asyncio
import time

from fakeredis import FakeStrictRedis


NUM_OF_REDIS_COMMANDS = 5000


async def async_pipeline_redis(redis_instance):
    pipeline = redis_instance.pipeline()

    for i in range(NUM_OF_REDIS_COMMANDS):
        pipeline.get('test')

    return pipeline.execute()


def sync_pipeline_redis(redis_instance):
    sync_pipeline = redis_instance.pipeline()

    for i in range(NUM_OF_REDIS_COMMANDS):
        sync_pipeline.get('test')
    return sync_pipeline.execute()


async def benchmark_pipeline():
    sync_redis = FakeStrictRedis()

    async_redis = FakeStrictRedis()

    s = time.time()
    sync_pipeline_redis(sync_redis)
    sync_pipe_time = time.time() - s
    print(f'sync time = {sync_pipe_time}')

    s = time.time()
    await async_pipeline_redis(async_redis)
    async_pipe_time = time.time() - s
    print(f'async time = {async_pipe_time}')

    print((async_pipe_time - sync_pipe_time) * 1000)

asyncio.run(benchmark_pipeline())`

**Comment by nrccua-timr** [comment]
oh wait, I think I see my blunder

**Comment by nrccua-timr** [comment]
Yeah I had an obvious bug with using same redis not aioredis connection.  When I switched to a real redis resource with the appropriate sync vs async logic I now see the same benchmark results roughly, which is great.  I'll keep using aioredis and hopefully aioredis has a release this quarter with these improvements.

**Comment by nrccua-timr** [comment]
@seandstewart  @Andrew-Chen-Wang  @popravich hi y'all.  Wanted to give you my perspective on the direction of this project.  After reading through #891 I'm pretty disheartened that such an amazing project would go somewhat unmaintained for a year when it has so much potential.  The speed of pipeline is terrible in comparison to the sync version, which is unacceptable for a project being used by so many people and has over 1k stars.  I'm not saying this primarily to complain as I want this project to succeed.  If Sean's PR was migrated to another fresh async redis project I would migrate all my aioredis integration to it tomorrow because the need for optimal performance is that important... it is one of the reasons for async in the first place, to optimize IO bound processing.

**Comment by popravich** [comment]
Pipeline performance is known problem and it will be fixed.
I just dont understand why you all want aio-redis-py so much but instead of adding async support to redis-py (where that PR belongs to) everyone just want to use it under this name.

**Comment by nrccua-timr** [comment]
When will the transaction performance issue be fixed?  A few days, months, in a year?

Get Outlook for Android<https://aka.ms/ghei36>
________________________________
