### ISSUE TITLE
please be more careful about releases

### ISSUE THREAD

**Issue by samuelcolvin** [aio-libs/aioredis-py#675]
Here are the changes between `v1.3.0` and `v1.3.1`: https://github.com/aio-libs/aioredis/compare/v1.3.0...v1.3.1
* 36 commits
* to 48 files
* totalling 747 additions and 1,261 deletions

There are also significant changes to the public API like changes to the `loop` attribute.

This not at all what you would expect in a patch release!

Also there are no docs on `v1.3.1` on [the releases page](https://aioredis.readthedocs.io/en/v1.3.0/migration.html).

Would it be possible to following a versioning approach closer to semvar in future?

**Comment by rubik** [comment]
@samuelcolvin I am considering moving away from aioredis even though I use it in pretty much all my projects. The library is completely stale, does not have cluster support, and I suspect it leaks connections. The maintainers are not active. The last couple of releases were done because everyone was asking for it.

**Comment by bsergean** [comment]
I wonder if we should fund the project a bit too, by sending some bucks to the creator to motivate him. Open source is hard.

I'm looking for cluster support too myself, and aredis seems very interesting and active, but what if one year from now the same thing happens to aredis.

**Comment by bsergean** [comment]
1.3.1 fixed some annoying warnings on python 3.8

**Comment by bsergean** [comment]
Maybe new maintainers could help the author, and it's time for folks to help / step up ?
