### ISSUE TITLE
create_redis taking exactly 2 seconds on Windows

### ISSUE THREAD

**Issue by oTree-org** [aio-libs/aioredis-py#728]
On my Windows computer (aioredis==1.3.1, Python 3.7), the following code always takes slightly over 2 seconds to run:

```
await aioredis.create_redis(address='redis://localhost:6379')
```
It's like 2.006, 2.005, 2.011, 2.015, etc. Never under 2 seconds.

When I use the python redis library it's instantaneous:

    redis.StrictRedis('redis://localhost:6379')

It's also instantaneous when I enter `redis-cli` at the command line and type `ping`.

On my Mac, aioredis.create_redis is very fast.

Do you have any ideas why it is so slow on Windows? I am trying to resolve a bottleneck on my django-channels app.

**Comment by Andrew-Chen-Wang** [comment]
Windows is tested on here (Redis 2) and seems fast. If you're using the Redis channels layer, that could be the reason why...? I also thought it could have been your code because those numbers are all really close to each other which means something else must be blocking for two seconds... I don't think it's an aioredis problem.
