### ISSUE TITLE
ConnectionPool: handling reconnections

### ISSUE THREAD

**Issue by 0xfadeef** [aio-libs/aioredis-py#733]
Hello everybody!

In my project I really need to handle situations when Redis server becomes unavailable. I searched the repo's issues and found (here #406 and here #635) that apparently `ConnectionPool` is able to do reconnections. However, examining the code, I can not figure out how and where it does this and also my tests show that reconnection is not actually performed (`execute` just raises `OSError` and that's it).

Am I missing something? Can someone please elaborate on this?

Thank you.

**Comment by wyqsmith** [comment]
Same Question...

**Comment by zzlpeter** [comment]
> Hello everybody!
> 
> In my project I really need to handle situations when Redis server becomes unavailable. I searched the repo's issues and found (here #406 and here #635) that apparently `ConnectionPool` is able to do reconnections. However, examining the code, I can not figure out how and where it does this and also my tests show that reconnection is not actually performed (`execute` just raises `OSError` and that's it).
> 
> Am I missing something? Can someone please elaborate on this?
> 
> Thank you.

has this issue been resolved ?

**Comment by Andrew-Chen-Wang** [comment]
I think the problem lies here: yes, the pool instance handles "reconnection" but it fails to execute the command you originally sent. The "reconnection" that the original owner talks about in other issues lies in the acquire/drop mechanism of Redis connections; every time you `await pool.acquire()` a new connection, you release and drop all closed ones and assume the one you have is perfectly fine. You can look at the code here: https://github.com/aio-libs/aioredis/blob/f5907fa8631a6f36684e081ec78e4d9267c6a992/aioredis/pool.py#L422-L437

Correct me if I'm wrong @seandstewart but I believe what they're asking for (execute the command) was purposefully not implemented to not allow a DOS attack against the Redis server.
