### ISSUE TITLE
RedisJSON / ReJSON

### ISSUE THREAD

**Issue by TensorTom** [aio-libs/aioredis-py#753]
Version: 1.3.1

I know that there are not currently any methods for [rejson aka RedisJSON](https://oss.redislabs.com/redisjson/). This is a feature request for that and question of:

Should it be okay to use the interface classes (Such as `execute`) for now to use rejson?

**Comment by agentspawn** [comment]
This could help: https://gist.github.com/agentspawn/269559fb75aa01a28e94f6416296c4fa

**Comment by shaqarava** [comment]
Made [this branch](https://github.com/shaqarava/aioredis/tree/rejson). Haven't tested yet.

**Comment by shaqarava** [comment]
I'm having trouble getting it working. When I use the class on its own by passing an aioredis connection to my class, it works but when I try to use it as part of aioredis: https://github.com/shaqarava/aioredis/blob/rejson/aioredis/commands/rejson.py I get an error on my first attempt.

`result = await redis.jmget('mykey1', 'mykey2', path='.')`

Throws error of wrong number of variables (2) passed to json.dumps where it expects 1. Which is weird since that method uses loads though I'm going off of memory. Will test again later. Anyone want to help make this into a PR?

**Comment by Andrew-Chen-Wang** [comment]
Prob won't become a PR since it's not integrated with Redis itself, so not testable for us maybe perhaps... (e.g. planning on moving to a structure similar to redis-py, but the [Redis-lab docs](https://oss.redislabs.com/redisjson/#python-example) shows to use `execute_command` since redis-py just doesn't offer this)?

Besides that, I think you might've just forgot where the error is coming from...? It could also be because you've been returned None rather than a list (not tested, but also not likely).

**Comment by romkazor** [comment]
> Throws error of wrong number of variables (2) passed to json.dumps where it expects 1. Which is weird since that method uses loads though I'm going off of memory. Will test again later. Anyone want to help make this into a PR?

If replace json with a ujson that everything is OK.

**Comment by seandstewart** [comment]
As of #891 this library is a full asyncio port of redis-py, so any examples found in Redis Labs' documentation should Just Work ™️ . Likely the issue here was that you needed your json encoded to bytes, which ujson does by default, I believe.
