### ISSUE TITLE
 multi process with websocket have more 8,000 time wait

### ISSUE THREAD

**Issue by XingDongZhe** [aio-libs/aioredis-py#803]
my django project use django-channels to  Information exchange through webscoket, I use redis as message middleware.
when I start 15 same processes for sending msg to front end, then i found that there are more 8000 tcp time_wait connection,
so my project trobule with `Cannot assign requested address`, please help me out

**Comment by XingDongZhe** [comment]
Today I use Redis monitor command, found that so much to execute ZREMRANGEBYSCORE and ZRANGE

**Comment by Andrew-Chen-Wang** [comment]
I don't use Django-channels as I've implemented a native way to handle them. I believe channels uses some LPUSH and LPOP command rather than Pub/Sub, and furthermore might not actually be closing these connections: https://github.com/django/channels_redis/issues/83 it seems to be a channels issue of just not closing the connection properly.

A quick fix if you would like to continue using Django channels is find a setting to close the Redis connection automatically after a certain amount of time.

You can check out my native implementation at [cookiecutter-django](https://github.com/pydanny/cookiecutter-django) to help with your chat application. I highly advise you to use a Pub/Sub connection by manually coding the channels layer rather than use django-channels Redis instance as channels is doing some LPOP and LPUSH command, which might be more inefficient. And then you want to manually close the connection since channels might not be doing so.

Have fun!
