### ISSUE TITLE
CancelledError when executing commands v1.3.1

### ISSUE THREAD

**Issue by atezerjani** [aio-libs/aioredis-py#938]
I'm using a redis connection pool of maxsize 10 to access the local redis server, and once in a while I get CancelledError running redis commands: 
This is the stacktrace of the exception:
_`await redis.set(key, json_fields)
File ".../aioredis/util.py", line 52, in wait_ok
res = await fut
concurrent.futures._base.CancelledError`_
it usually reach to a point with a lot of these errors and then automatically resolve shortly. I have no clue what the possible source of this exception is. Does anybody has any thought?

**Comment by Andrew-Chen-Wang** [comment]
We don't support aioredis 1.3.1 anymore. Unless you give me more info, I can only direct you to help test out v2.0.0a1 which isn't stable. So please provide a little bit of code or context to help me debug

**Comment by atezerjani** [comment]
I have a sanic rest server that on some api, I write an xml into the redis using this code block:
`async def cache_dialplan_xml(redis, xml_id, xml_content):
  key = f'dialplan_xml_{xml_id}'

  if await redis.exists(key):
    return None

  await cache_object(redis, key, {'buffer': xml_content})
  await redis.expire(key, XML_CACHE_LIFETIME_SECS)
  return xml_id

async def cache_object(redis, key, fields):
  if await redis.exists(key):
    return False
  fields['__last_update_time'] = str(datetime.now().strftime('%s'))
  json_fields = pickle.dumps(fields)
  await redis.set(key, json_fields)
  return True
`
the redis object in this method is created using create_redis_pool like this:
`      self.redis = await aioredis.create_redis_pool(f'redis://{self.redis_host}:{self.redis_port}',
                                                    db=int(self.redis_db),
                                                    password=self.redis_pw,
                                                    maxsize=20)
`
one in a while when I have some concurrent request to write into redis, this CancelledError exception happens in either redis.exist or redis.set methods

**Comment by Andrew-Chen-Wang** [comment]
I'm unfortunately not that well versed in 1.3.1. My guesses:

1. In your sonic server, at the end of the request, you're not closing the redis pool. You should explicitly close it.
2. The `pickle.dumps` could be causing trouble since that creates bytes literal. Instead, you should use `json.dumps` which creates a string. Based on the old documentation: https://aioredis.readthedocs.io/en/v1.3.1/mixins.html#aioredis.commands.StringCommandsMixin.set You could also try just inputting the dictionary itself. I'm pretty sure Redis supports bytes as values, so I'm wondering if it has to do with parsing errors on aioredis's side.

Again, we won't be working on aioredis 1.3.1 so I'd look out for the alpha version of this package 2.0.0a1. We'll hopefully have stable version by May/June.

**Comment by atezerjani** [comment]
Just a quick note that the cancelled error happens right after two seconds that the redis Coroutine  command executed

**Comment by Andrew-Chen-Wang** [comment]
So neither of my guesses worked? Strange. I would assume that error was from an unclosed connection. Do you mind doing the following:

1. Check how many connections are open on Redis right now
2. Make those caching calls happen
3. Check how many connections are open on Redis now
4. Wait 4 seconds and try again Check how many connections are open on Redis now
5. Shut down the entire web server
6. Check how many connections are open on Redis now

That should test to see if the first guess was the error. The second guess is to try using `json.dumps`. It would be helpful if you let me know the results of these guesses because at the moment I'm assuming neither worked.

Those are unfortunately my only two guesses, too, mate. I really don't know and unfortunately can't put time into debugging 1.3.1 since it's completely different from 2.0.0a1 and I can't be bothered to trying to decipher old code again. Please update to aioredis 2.0.0a1. Many people have apparently already integrated it with their systems and  working fine.

**Comment by atezerjani** [comment]
Thanks Andrew, so to answer your questions:
1. We're not closing the pool after each request, why should we? We have one pool through the whole lifetime of the rest server. We create it when the server starts and don't explicitly close it, until the process is ended.
2. It's definitely not pickle, because we were using json.dumps and we had exactly the same issue.

I'm thinking about a timeout somewhere causing it, because the cancellation error happens exactly 2 seconds after the command gets executed.

**Comment by Andrew-Chen-Wang** [comment]
Ah perfect. Guess 1 was correct. Python web servers close their pools and all connections after each request because the thread is spun down. The entire thing is dropped and waits for a worker like Gunicorn to spin a new thread back up. Don't believe me? Take a look at Django: https://github.com/django/django/blob/1351f2ee163145df2cf5471eb3e57289f8853512/django/core/cache/__init__.py#L52-L59

And yes, all Python web servers are like this. All of them. Make sure you close your connection after each request.

> We have one pool through the whole lifetime of the rest server. We create it when the server starts and don't explicitly close it, until the process is ended.

That's the mistake. The server is just a server. The lifetime is of a single request, not of a single spin up. Try it. Sure the TCP connection *seems* closed because the thread should shut everything down, but the truth is Redis now has a dangling connection.

Still don't believe me?

You probably deploy using some kind of ASGI.py file. That ASGI file is just a `main.py` or a `if __name__ == "__main__"` main/intro function call. Your deployment is simply calling that file every time a new request comes in.

**Comment by Andrew-Chen-Wang** [comment]
Stale, closing, I think the question's been answered etc.
